<Project Sdk="Microsoft.NET.Sdk.Web">

    <PropertyGroup>
        <TargetFramework>net10.0</TargetFramework>
        <Nullable>enable</Nullable>
        <ImplicitUsings>enable</ImplicitUsings>
      <UserSecretsId>04767401-4d33-4f42-ba42-ac32b0ebb582</UserSecretsId>
  </PropertyGroup>

    <ItemGroup>
        <PackageReference Include="MediatR" Version="14.2.0" />
        <PackageReference Include="Microsoft.AspNetCore.OpenApi" Version="10.0.11" />
        <PackageReference Include="Microsoft.VisualStudio.Web.CodeGeneration.Design" Version="10.0.2" />
    </ItemGroup>

    <ItemGroup>
      <Folder Include="Controllers\" />
    </ItemGroup>

    <ItemGroup>
      <ProjectReference Include="..\Clase2.Application\Clase2.Application.csproj" />
      <ProjectReference Include="..\Clase5.Infrastructure\Clase5.Infrastructure.csproj" />
    </ItemGroup>

</Project>
